apiVersion: v1
kind: ConfigMap
metadata:
  name: danted-config
  namespace: marzban
data:
  danted.conf: |
    logoutput: stderr
    internal: eth0 port = 1080
    external: eth0
    method: username none
    clientmethod: none
    user.privileged: root
    user.unprivileged: nobody
    client pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect disconnect error
    }
    pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect disconnect error
    }
