version: '3.3'

services:
  x-ui:
    image: x-ui-tunnel:latest
    container_name: x-ui
    ports:
      - "2023:2023"
    volumes:
      - x-ui-data:/etc/x-ui/
    restart: always

  chisel-client:
    image: jpillora/chisel
    container_name: chisel-client
    command: ["client", "-v", "--skip-verify", "https://vds1.iri1968.dpdns.org:80", "R:8001:x-ui:2023"]
    restart: always

volumes:
  x-ui-data:
